### ISSUE TITLE
Error when adding multiple xibs to a single storyboard

### ISSUE THREAD

**Issue by fvvliet** [novemberfiveco/xib2Storyboard#2]
When using this option I receive the following error in XCode 9.3

<img width="423" alt="screen shot 2018-05-10 at 14 57 22" src="https://user-images.githubusercontent.com/2924822/39870679-7ef17a9c-5462-11e8-98e0-6f952fbe8da1.png">

**Comment by DriesVS** [comment]
Hi Frank!

It seems like there are duplicate ID's in the Storyboard. While we do randomize certain ID's when merging multiple Xib's to prevent this from happening, there could be some edge cases where ID's are not randomized.

Did you previously copy views from one Xib to another? We found this causes issues occasionally but we fixed those issues by randomizing XML-element ID's for view controllers, gesture recognizers, subviews etc.

Could you provide me with the Xib's you are having this issue with so I can look into debugging them?
Feel free to email them to dries@novemberfive.co

**Comment by fvvliet** [comment]
Hello Dries, I have sent you the xib's. Any update on this issue ?
Thanks
Frank

**Comment by wyllys66** [comment]
Im having same issue, trying to export to an existing storyboard.

**Comment by DriesVS** [comment]
Hi Frank & Wyllys!

Thanks Frank for sending over your Xib's to help make debugging easier.

The issue was indeed related to multiple objects having the same ID. On top of that there was an issue that when the same images are used in multiple Xib's IB simply fails due to duplicates images. Those two issues are now fixed! You can download the binary from the latest commit on master. Feel free to let me know if things are not working as expected...
